/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package salies.client;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.*;
import java.io.FileWriter;
import java.io.IOException;
import java.awt.Desktop;
import java.net.URI;
import java.util.HashMap;

/**
 *
 * @author Daniel
 */
public class MainWindow extends javax.swing.JFrame {
    private ClientController controller;

    public MainWindow(ClientController controller) {
        this.controller = controller;

        FlatLightLaf.setup();
        initComponents();
        customInitComponents();
    }

    // Como o NetBeans pede para que eu não altere o código dele,
    // criaria uma initComponentes própria
    private void customInitComponents() {
        // ProfileRenderer: travando o pane
        //resPane.setEditable(false);
        // Preparando-o para receber apenas HTML
        //resPane.setContentType("text/html");
    }

    // Manda a mensagem para que o controlador encaminhe ao servidor
    private void sendMessage(String type, String body) {
        try {
            controller.messageHandler(type, body);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao enviar mensagem.\nVerifique o log para mais detalhes.",
                    "Erro", JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

    // ProfileRenderer: seta o HTML no pane
    public void setRenderedHTML(String html) {
        //resPane.setText(html);
        // Salvando em arquivo temporário
        try{
            FileWriter fw = new FileWriter("temp.html");
            fw.write(html);
            fw.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao renderizar HTML.\nVerifique o log para mais detalhes.",
                    "Erro", JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }

        // Abrindo o arquivo temporário no navegador padrão do sistema
        try {
            Desktop.getDesktop().browse(URI.create("temp.html"));
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao abrir o navegador.\nVerifique o log para mais detalhes.",
                    "Erro", JOptionPane.ERROR_MESSAGE
            );
            e.printStackTrace();
        }
    }

    public void setStatsResult(String result) {
        // ...
    }

    public void setHashResult(String hash) {
        // ...
    }

    public void setVerifyHashResult(String result) {
        Boolean res = Boolean.parseBoolean(result);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        htmlPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        realNameLabel = new javax.swing.JLabel();
        realNameField = new javax.swing.JTextField();
        bioLabel = new javax.swing.JLabel();
        bioScrollPane = new javax.swing.JScrollPane();
        bioTextArea = new javax.swing.JTextArea();
        locLabel = new javax.swing.JLabel();
        locField = new javax.swing.JTextField();
        avatarLabel = new javax.swing.JLabel();
        avatarBox = new javax.swing.JComboBox<>();
        nFollowersLabel = new javax.swing.JLabel();
        nFollowersBox = new javax.swing.JSpinner();
        nFollowingLabel = new javax.swing.JLabel();
        nFollowingBox = new javax.swing.JSpinner();
        renderBtn = new javax.swing.JButton();
        hashPanel = new javax.swing.JPanel();
        guideLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TP Final CDeP - Cliente");

        jTabbedPane.setPreferredSize(new java.awt.Dimension(520, 500));

        htmlPanel.setPreferredSize(new java.awt.Dimension(500, 212));

        usernameLabel.setText("Nome de usuário:");

        usernameField.setText("sonicsalies");

        realNameLabel.setText("Nome real:");

        realNameField.setText("Daniel Serezane");

        bioLabel.setText("Bio");

        bioTextArea.setColumns(20);
        bioTextArea.setRows(5);
        bioTextArea.setText("It's not a lake, it's an ocean.");
        bioScrollPane.setViewportView(bioTextArea);

        locLabel.setText("Localização");

        locField.setText("Martinópolis, SP");

        avatarLabel.setText("Avatar");

        avatarBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Zelda", "Purah", "Riju" }));

        nFollowersLabel.setText("nº de seguidores");

        nFollowersBox.setModel(new javax.swing.SpinnerNumberModel(666, 0, null, 1));

        nFollowingLabel.setText("nº de seguindo");

        nFollowingBox.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        renderBtn.setText("Renderizar");
        renderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renderBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout htmlPanelLayout = new javax.swing.GroupLayout(htmlPanel);
        htmlPanel.setLayout(htmlPanelLayout);
        htmlPanelLayout.setHorizontalGroup(
            htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(htmlPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bioLabel)
                    .addGroup(htmlPanelLayout.createSequentialGroup()
                        .addComponent(bioScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(renderBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(htmlPanelLayout.createSequentialGroup()
                                .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nFollowersLabel)
                                    .addComponent(nFollowingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nFollowingBox)
                                    .addComponent(nFollowersBox)))))
                    .addGroup(htmlPanelLayout.createSequentialGroup()
                        .addComponent(usernameLabel)
                        .addGap(5, 5, 5)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(realNameLabel)
                        .addGap(5, 5, 5)
                        .addComponent(realNameField))
                    .addGroup(htmlPanelLayout.createSequentialGroup()
                        .addComponent(locLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(avatarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avatarBox, 0, 77, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        htmlPanelLayout.setVerticalGroup(
            htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(htmlPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(realNameLabel)
                    .addComponent(realNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locLabel)
                    .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avatarLabel)
                    .addComponent(avatarBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(bioLabel)
                .addGap(5, 5, 5)
                .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(htmlPanelLayout.createSequentialGroup()
                        .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nFollowersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nFollowersLabel))
                        .addGap(10, 10, 10)
                        .addGroup(htmlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nFollowingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nFollowingLabel))
                        .addGap(10, 10, 10)
                        .addComponent(renderBtn))
                    .addComponent(bioScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jTabbedPane.addTab("Template HTML", htmlPanel);

        javax.swing.GroupLayout hashPanelLayout = new javax.swing.GroupLayout(hashPanel);
        hashPanel.setLayout(hashPanelLayout);
        hashPanelLayout.setHorizontalGroup(
            hashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );
        hashPanelLayout.setVerticalGroup(
            hashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 211, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Hashing", hashPanel);

        guideLabel.setText("Escolha um dos três serviços abaixo. Interaja com a interface para executar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guideLabel)
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(guideLabel)
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renderBtnActionPerformed
        StringBuilder msgBuilder = new StringBuilder();
        // Construindo o query
        msgBuilder.append(realNameField.getText().replace(" ", "{{}}"));
        msgBuilder.append(" ");
        msgBuilder.append(usernameField.getText().replace(" ", ""));
        msgBuilder.append(" ");
        msgBuilder.append(bioTextArea.getText().replace(" ", "{{}}"));
        msgBuilder.append(" ");
        msgBuilder.append(locField.getText().replace(" ", "{{}}"));
        msgBuilder.append(" ");
        msgBuilder.append(avatarBox.getSelectedIndex());
        msgBuilder.append(" ");
        msgBuilder.append(nFollowersBox.getValue());
        msgBuilder.append(" ");
        msgBuilder.append(nFollowingBox.getValue());

        // Enviando a mensagem
        try {
            this.controller.messageHandler("network", msgBuilder.toString());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Erro ao enviar mensagem: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_renderBtnActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> avatarBox;
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JLabel bioLabel;
    private javax.swing.JScrollPane bioScrollPane;
    private javax.swing.JTextArea bioTextArea;
    private javax.swing.JLabel guideLabel;
    private javax.swing.JPanel hashPanel;
    private javax.swing.JPanel htmlPanel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField locField;
    private javax.swing.JLabel locLabel;
    private javax.swing.JSpinner nFollowersBox;
    private javax.swing.JLabel nFollowersLabel;
    private javax.swing.JSpinner nFollowingBox;
    private javax.swing.JLabel nFollowingLabel;
    private javax.swing.JTextField realNameField;
    private javax.swing.JLabel realNameLabel;
    private javax.swing.JButton renderBtn;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
